import { GoogleGenerativeAI } from '@google/generative-ai'

export function isGeminiAvailable(): boolean {
  return !!process.env.GEMINI_API_KEY
}

/**
 * Generate an image with Gemini from a reference photo + free-form prompt.
 * Used by both the legacy hand-model flow and the new 3-scene generator.
 */
export async function generateImageFromReference(
  imageBase64: string,
  mimeType: string,
  prompt: string,
): Promise<Buffer> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured')
  }

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY)
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-image' })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const requestBody: any = {
    contents: [
      {
        role: 'user',
        parts: [
          { inlineData: { mimeType, data: imageBase64 } },
          { text: prompt },
        ],
      },
    ],
    generationConfig: { responseModalities: ['image', 'text'] },
  }

  const result = await model.generateContent(requestBody)
  const parts = result.response.candidates?.[0]?.content?.parts || []

  for (const part of parts) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const inlineData = (part as any).inlineData
    if (inlineData?.data) {
      return Buffer.from(inlineData.data, 'base64')
    }
  }
  throw new Error('No image generated by Gemini')
}

export async function generateHandModelImage(
  imageBase64: string,
  mimeType: string
): Promise<Buffer> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured')
  }

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY)
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-image' })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const requestBody: any = {
    contents: [
      {
        role: 'user',
        parts: [
          {
            inlineData: {
              mimeType,
              data: imageBase64,
            },
          },
          {
            // This is an *image transplant* task, NOT an image generation task.
            // Gemini's default behavior is to "creatively re-imagine" details —
            // we fight that with very explicit framing + a structured rubric +
            // an explicit failure mode (return original if you can't preserve).
            text: `TASK: Image transplant. Place the EXISTING press-on nail design from the input image onto a hand model.

CRITICAL CONSTRAINTS — read carefully:
1. The nails in the input photo are the FINAL product. Do NOT redesign, restyle, recolor, repaint, or "improve" them.
2. Copy the nail design pixel-for-pixel: every color, gradient, glitter speck, hand-painted line, gem placement, base shade, tip shape, and length must be IDENTICAL to the input.
3. Treat the nails as a sticker / decal that you are placing onto fingertips. You may ONLY change orientation/perspective to match the hand pose — never the artwork itself.
4. If a nail in the input has 3 dots, your output has 3 dots in the same positions. If it has a French tip, your output has the SAME tip line. If it's pink ombré, your output is pink ombré in the same direction.

SCENE COMPOSITION:
- A relaxed, elegant female hand visible from fingertip to mid-forearm
- Soft natural lighting, no harsh shadows
- Clean cream / off-white minimal background (no jewelry, no props)
- Hand pose should naturally show all 5 nails clearly (e.g. fingers slightly spread, palm down or three-quarter angle)
- Skin tone: neutral medium-light (similar to indie nail brand reference photos)
- Photo style: professional product shot, soft matte, magazine-quality

OUTPUT RULES:
- Output ONLY the image. No text.
- If you cannot preserve the exact nail design from the input, return the input image UNCHANGED rather than producing a re-imagined version.
- Do not add a watermark, signature, or text overlay.`,
          },
        ],
      },
    ],
    generationConfig: {
      responseModalities: ['image', 'text'],
    },
  }

  const result = await model.generateContent(requestBody)

  const response = result.response
  const parts = response.candidates?.[0]?.content?.parts || []

  for (const part of parts) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const inlineData = (part as any).inlineData
    if (inlineData?.data) {
      return Buffer.from(inlineData.data, 'base64')
    }
  }

  throw new Error('No image generated by Gemini')
}
