import { GoogleGenerativeAI } from '@google/generative-ai'

export function isGeminiAvailable(): boolean {
  return !!process.env.GEMINI_API_KEY
}

export async function generateHandModelImage(
  imageBase64: string,
  mimeType: string
): Promise<Buffer> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured')
  }

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY)
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-image' })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const requestBody: any = {
    contents: [
      {
        role: 'user',
        parts: [
          {
            inlineData: {
              mimeType,
              data: imageBase64,
            },
          },
          {
            text: 'Generate a photorealistic image of a hand model wearing these press-on nails. The hand should be elegantly posed against a clean, aesthetic background. Make it look like a professional nail salon Instagram photo.',
          },
        ],
      },
    ],
    generationConfig: {
      responseModalities: ['image', 'text'],
    },
  }

  const result = await model.generateContent(requestBody)

  const response = result.response
  const parts = response.candidates?.[0]?.content?.parts || []

  for (const part of parts) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const inlineData = (part as any).inlineData
    if (inlineData?.data) {
      return Buffer.from(inlineData.data, 'base64')
    }
  }

  throw new Error('No image generated by Gemini')
}
